"""
routes_report.py
────────────────
Cursor-paginated HTTP access to a *_report.parquet file, addressed by the
same (data_type, ip_name, file_id) layout used for storage:

    GET /api/report/{data_type}/{ip_name}/{file_id}/page   (beneficiary / banks / financials)
    GET /api/report/{data_type}/{file_id}/page             (certificates — no ip_name)

    ?page_size=20&cursor=<token>&raw=false

Pagination contract
-------------------
- First page: omit `cursor`.
- Each response carries pagination.next_cursor.
- Fetch the next page by passing that token back as `cursor`.
- next_cursor == null  →  last page reached.
The cursor is opaque; clients echo next_cursor back unchanged, never parse it.
- Alternatively, pass `page=<n>` (1-based) to jump directly to any page —
  forward, backward, or anywhere in between — without walking through
  cursors. `page` wins if both `page` and `cursor` are given.

Duplicates endpoint
--------------------
    GET /api/report/{data_type}/{ip_name}/{file_id}/duplicates
    GET /api/report/{data_type}/{file_id}/duplicates          (certificates)

Returns the *entire* `_duplicates.parquet` file as one JSON payload — no
pagination, no cursor. This file is a raw row-subset of the cleaned dataset
(rows flagged as UUID-duplicate OR CNIC-duplicate), so it carries whatever
columns the original data had — it has NO `is_dup_cnic` flag and no
dedicated CNIC column of its own. It's diagnostic data, not a substitute for
browsing the full report.

Duplicate-CNIC summary and data
---------------------------------
Previously this was read from one hardcoded, global JSON file that had to be
regenerated by hand any time an IP's data changed.

It is now computed live from every IP's own `{ip_name}_report.parquet`
under the requested data_type (discovered via iter_all_outputs) — every
row, not a pre-filtered subset — since only scanning the full population
lets us catch a CNIC that appears once in one IP and once in another (a
genuine cross-IP duplicate that no single IP's own per-file processing
could ever see on its own). The actual CNIC value is pulled out of each
row's `validation_status` per-filter detail, by matching any filter whose
`col` name contains "cnic" (case-insensitively — e.g. "DA_CNIC" — so this
isn't hardcoded to one column name), then normalized (whitespace, float
".0" artifacts, and non-digit separators stripped) so the same real CNIC
compares equal across IPs regardless of formatting differences.

The response shapes are deliberately kept separate:
  - `/page` attaches `duplicate_cnic_summary`  — rolled-up totals only.
  - `/duplicates` attaches `data` — a flat per-CNIC breakdown (cnic,
    duplicate_count, duplicate_in_no_of_ips, ip_names, ip_names_text), with
    NO aggregate summary block; that belongs solely to `/page`.
  - `/duplicates/cnic/records`, `/duplicates/cnic/occurrences`,
    `/duplicates/cnic/single-ip`, `/duplicates/cnic/cross-ip` — new,
    paginated drill-downs. Each backs exactly one number in
    duplicate_cnic_summary, so you can page through the actual records
    behind that count instead of just seeing the total:
        total_duplicate_cnic_records          -> /duplicates/cnic/records
        total_duplicate_occurrences           -> /duplicates/cnic/occurrences
        cnics_duplicated_in_single_ip         -> /duplicates/cnic/single-ip
        cnics_duplicated_across_multiple_ips  -> /duplicates/cnic/cross-ip
    All four use the exact same page/cursor/page_size pagination contract
    as `/page` (see paginate_list in report/pagination.py), including
    direct page-number jumps.
All are built from one shared, cached pool computation
(`_compute_duplicate_cnic_pool`) so the underlying report scan only runs
once per data_type per cache cycle, not once per endpoint.

Results are cached in-process, keyed by the (path, mtime) signature of
every report file that contributed — the cache rebuilds automatically the
moment any one of those files is rewritten, added, or removed.

Performance
-----------
Each parquet is loaded once, then cached in-process keyed by (path, mtime).
Repeated requests for an unchanged file are served from memory. If the file
is rewritten, its mtime changes and the cache rebuilds. Report pages and
duplicates dumps use separate caches since they're different files with
different access patterns (report is sorted once, duplicates is a raw dump).
The occurrence-records drill-down (full row per duplicate CNIC occurrence)
has its own cache too, since it's a second, heavier scan of every IP's
_cleaned.parquet beyond what the summary pool alone needs — it's only ever
computed if that specific endpoint is actually called.
"""
from __future__ import annotations

import json
import re
import threading
from pathlib import Path
from typing import Any, Optional

import pandas as pd
from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import JSONResponse

from output_writer import resolve_dir, iter_all_outputs, InvalidDataLocation
from report.pagination import load_report, get_page, paginate_list, JSON_COLUMNS

router = APIRouter()

# load-once cache: path -> (mtime, sorted DataFrame)
_cache: dict[str, tuple[float, pd.DataFrame]] = {}
_cache_lock = threading.Lock()

# separate cache for duplicates dumps — not sorted/keyed the way report is
_dup_cache: dict[str, tuple[float, pd.DataFrame]] = {}
_dup_cache_lock = threading.Lock()

# ---------------------------------------------------------------------------
# Dynamic duplicate-CNIC summary
#
# IMPORTANT: this is built from every IP's FULL _cleaned.parquet (every
# row), NOT from _duplicates.parquet. Each IP's _duplicates.parquet only
# contains rows that IP's OWN cleaning run already flagged as duplicates
# within its own data — so a CNIC appearing once in Trdp and once in Hands
# is never flagged by either IP individually, and never appears in either
# IP's _duplicates.parquet at all. Cross-referencing that file can
# therefore NEVER surface genuine cross-IP duplicates, no matter how good
# the matching logic is — the rows just aren't there to find.
#
# _cleaned.parquet is used instead of _report.parquet because the cleaned
# file stores the CNIC as a plain column (e.g. "DA_CNIC" — see
# _find_cnic_column) rather than buried inside a validation_status JSON
# string. That means a direct vectorized column read instead of
# json.loads()-ing every single row just to pull one field back out.
#
# Either way, we pull the CNIC out of every single row, from every IP's
# file, and do the "does this repeat, and across how many different IPs"
# computation ourselves, from the full population, not a pre-filtered
# subset.
# ---------------------------------------------------------------------------

# Matches any column name that refers to a CNIC field, regardless of exact
# naming (e.g. "DA_CNIC", "CNIC", "Cnic_Number", ...).
_CNIC_COL_RE = re.compile(r"cnic", re.IGNORECASE)

# Matches a lone trailing ".0" (or ".00", etc.) left over when a numeric
# CNIC value got upcast to float somewhere in the pipeline (e.g.
# 4530358104832 -> 4530358104832.0). Stripped before comparison so the same
# CNIC read as float in one IP's file and as int/string in another's still
# matches.
_TRAILING_FLOAT_ZERO_RE = re.compile(r"\.0+$")

# Missing/null placeholder strings after str()'ing a value, checked
# case-insensitively (Python's None stringifies to "None", NaN to "nan", ...).
_MISSING_VALUE_TOKENS = {"", "nan", "none", "null", "na", "n/a"}

# cache key: data_type (lowercased) -> (signature, summary)
# signature = sorted tuple of (path, mtime) for every report file that went
# into the aggregate, so any add/remove/rewrite invalidates it.
_cnic_summary_cache: dict[str, tuple[tuple, dict]] = {}
_cnic_summary_lock = threading.Lock()

# cache key: data_type (lowercased) -> (signature, list-of-full-records)
# Separate from _cnic_summary_cache because this holds full row data for
# every occurrence of every duplicate CNIC (heavier), and is only ever
# populated if /duplicates/cnic/occurrences is actually called.
_cnic_occurrence_cache: dict[str, tuple[tuple, list[dict]]] = {}
_cnic_occurrence_lock = threading.Lock()

# cache key: data_type (lowercased) -> (signature, list-of-full-records)
# Rows whose CNIC came back missing/null after normalization, one entry
# per row (not deduped) — backs the "Missing CNICs" / "Null CNIC in IP"
# drill-down, same caching pattern as the occurrence cache.
_cnic_missing_cache: dict[str, tuple[tuple, list[dict]]] = {}
_cnic_missing_lock = threading.Lock()


def _normalize_cnic(raw: Any) -> Optional[str]:
    """Normalize a raw CNIC value into a comparable string, or None if it's
    effectively missing.

    Handles:
      - actual NaN/None
      - whitespace padding
      - float-artifact trailing ".0" from numeric upcasting
      - non-digit separators (dashes, spaces) so "12345-6789012-3" and
        "1234567890123" compare equal
    """
    if raw is None:
        return None
    s = str(raw).strip()
    if s.lower() in _MISSING_VALUE_TOKENS:
        return None
    s = _TRAILING_FLOAT_ZERO_RE.sub("", s)
    digits = re.sub(r"\D", "", s)
    return digits if digits else None


def _find_cnic_column(df: pd.DataFrame) -> Optional[str]:
    """Return the first column in a _cleaned.parquet dataframe whose name
    contains 'cnic' (case-insensitive), e.g. "DA_CNIC". Returns None if no
    such column exists in this dataframe.
    """
    for col in df.columns:
        if _CNIC_COL_RE.search(col):
            return col
    return None


def _cleaned_candidates(data_type: str) -> list[tuple[Optional[str], str, Path]]:
    """Every (ip_name, file_id, path) triple for this data_type's
    _cleaned.parquet files. Shared by the summary pool and the occurrence-
    records scan so both iterate the same file list.
    """
    try:
        return [
            (ip_name, file_id, p)
            for dt, ip_name, file_id, p in iter_all_outputs(kind="cleaned")
            if dt.lower() == data_type.lower()
        ]
    except Exception:
        return []


def _signature(candidates: list[tuple[Optional[str], str, Path]]) -> tuple:
    try:
        return tuple(sorted((str(p), p.stat().st_mtime) for _, _, p in candidates))
    except OSError:
        return tuple(sorted(str(p) for _, _, p in candidates))


def _compute_duplicate_cnic_pool(data_type: str) -> Optional[dict]:
    """Scan every IP's FULL _cleaned.parquet for this data_type, pool every
    row's CNIC value together, and return the raw duplicate-CNIC pool —
    i.e. every CNIC whose total occurrence count across ALL IPs combined is
    2 or more, along with the per-IP breakdown of where it showed up.

    Uses _cleaned.parquet rather than _report.parquet because the cleaned
    file carries the CNIC as a plain column (e.g. "DA_CNIC") — a direct,
    vectorized column read — instead of a value buried inside a
    validation_status JSON string that had to be json.loads()'d per row.
    Same data, far cheaper to scan.

    This is the single source of truth both the aggregate summary (used by
    /page) and the per-CNIC data list (used by /duplicates and the
    drill-down endpoints) are built from, so the underlying scan only
    happens once per data_type per cache cycle.

    Returns None only if no cleaned files exist at all for this data_type —
    a missing/unreadable file for one particular IP is just skipped, it
    never fails the whole computation.

    Return shape:
        {
          "duplicate_cnics": {cnic: {ip_name: occurrence_count, ...}, ...},
          "missing_cnics_count": int,
          "missing_by_ip": {ip_name: int, ...},
          "unique_ip_names": [str, ...],
        }
    """
    candidates = _cleaned_candidates(data_type)
    if not candidates:
        return None

    signature = _signature(candidates)

    with _cnic_summary_lock:
        cached = _cnic_summary_cache.get(data_type.lower())
        if cached and cached[0] == signature:
            return cached[1]

    # normalized cnic value -> {ip_name: occurrence_count}
    cnic_to_ip_counts: dict[str, dict[str, int]] = {}
    missing_cnics_count = 0
    missing_by_ip: dict[str, int] = {}
    ips_with_data: set = set()

    for ip_name, file_id, path in candidates:
        try:
            df = pd.read_parquet(path, engine="fastparquet")
        except Exception:
            continue  # one bad/corrupt file shouldn't sink the whole computation

        cnic_col = _find_cnic_column(df)
        if cnic_col is None:
            continue

        ip_key = ip_name or file_id
        ips_with_data.add(ip_key)

        # Direct vectorized column read — no per-row JSON parsing needed,
        # since the cleaned file stores CNIC as a plain column value.
        normalized = df[cnic_col].map(_normalize_cnic)

        missing_mask = normalized.isna()
        missing_count_here = int(missing_mask.sum())
        missing_cnics_count += missing_count_here
        missing_by_ip[ip_key] = missing_by_ip.get(ip_key, 0) + missing_count_here

        valid = normalized[~missing_mask]
        for cnic, count in valid.value_counts().items():
            per_ip = cnic_to_ip_counts.setdefault(cnic, {})
            per_ip[ip_key] = per_ip.get(ip_key, 0) + int(count)

    if not ips_with_data:
        return None

    # A CNIC counts as "duplicate" once its total occurrences across ALL
    # IPs combined is 2+ — whether that's two rows in the same IP, one row
    # each in two different IPs, or any other split.
    duplicate_cnics = {
        cnic: ip_counts
        for cnic, ip_counts in cnic_to_ip_counts.items()
        if sum(ip_counts.values()) >= 2
    }

    pool = {
        "duplicate_cnics": duplicate_cnics,
        "missing_cnics_count": missing_cnics_count,
        "missing_by_ip": missing_by_ip,
        "unique_ip_names": sorted(str(ip).lower() for ip in ips_with_data),
    }

    with _cnic_summary_lock:
        _cnic_summary_cache[data_type.lower()] = (signature, pool)

    return pool


def _get_duplicate_cnic_summary(data_type: str) -> Optional[dict]:
    """Aggregate CNIC-duplicate stats for this data_type — the summary
    block attached to /page responses only. Built from the shared pool in
    _compute_duplicate_cnic_pool.
    """
    pool = _compute_duplicate_cnic_pool(data_type)
    if pool is None:
        return None

    duplicate_cnics = pool["duplicate_cnics"]
    total_duplicate_cnic_records = len(duplicate_cnics)
    total_duplicate_occurrences = sum(sum(c.values()) for c in duplicate_cnics.values())
    cnics_duplicated_in_single_ip = sum(1 for c in duplicate_cnics.values() if len(c) == 1)
    cnics_duplicated_across_multiple_ips = sum(1 for c in duplicate_cnics.values() if len(c) > 1)

    return {
        "total_duplicate_cnic_records": total_duplicate_cnic_records,
        "total_duplicate_occurrences": total_duplicate_occurrences,
        "cnics_duplicated_in_single_ip": cnics_duplicated_in_single_ip,
        "cnics_duplicated_across_multiple_ips": cnics_duplicated_across_multiple_ips,
        "missing_cnics_count": pool["missing_cnics_count"],
        "unique_ip_names": pool["unique_ip_names"],
    }


def _get_duplicate_cnic_data(
    data_type: str,
    *,
    only: Optional[str] = None,
    ip_name: Optional[str] = None,
) -> Optional[list[dict]]:
    """Per-CNIC duplicate breakdown for this data_type, sorted by cnic:

        [
          {
            "cnic": "4320411145098",
            "duplicate_count": 3,
            "duplicate_in_no_of_ips": 1,
            "ip_names": ["safco"],
            "ip_names_text": "safco",
          },
          ...
        ]

    `only` filters which rows are included, backing the specific summary
    counts:
      - None            -> every duplicate CNIC (total_duplicate_cnic_records)
      - "single_ip"      -> only cnics_duplicated_in_single_ip (len(ip_names) == 1)
      - "cross_ip"       -> only cnics_duplicated_across_multiple_ips (len(ip_names) > 1)

    `ip_name`, if given, additionally restricts rows to only those that
    include this IP at all (case-insensitive match against pool keys) —
    e.g. ip_name="Hands" on the single_ip view returns only Hands' own
    single-IP duplicates; on the cross_ip view it returns only cross-IP
    duplicates that Hands happens to be one of the involved IPs for.
    duplicate_count/duplicate_in_no_of_ips stay as the CNIC's TOTAL across
    all IPs (not just this IP's share) — this only filters which CNICs are
    included, it doesn't re-scope the counts to this IP alone.

    Built from the same shared pool as the aggregate summary, just shaped
    differently (no aggregate block here; that belongs solely to /page).
    """
    pool = _compute_duplicate_cnic_pool(data_type)
    if pool is None:
        return None

    target = ip_name.strip().lower() if ip_name else None

    rows: list[dict] = []
    for cnic, ip_counts in pool["duplicate_cnics"].items():
        ip_names = sorted(ip_counts.keys())
        if only == "single_ip" and len(ip_names) != 1:
            continue
        if only == "cross_ip" and len(ip_names) <= 1:
            continue
        if target is not None and not any(n.lower() == target for n in ip_names):
            continue
        rows.append({
            "cnic": cnic,
            "duplicate_count": sum(ip_counts.values()),
            "duplicate_in_no_of_ips": len(ip_names),
            # Convenience field: the single IP this CNIC belongs to when
            # it's only duplicated within one IP (the common case for
            # /single-ip). Null when the CNIC spans multiple IPs (cross-IP
            # rows) since there's no single answer — use ip_names there.
            "ip_name": ip_names[0] if len(ip_names) == 1 else None,
            "ip_names": ip_names,
            "ip_names_text": ", ".join(ip_names),
        })

    rows.sort(key=lambda r: r["cnic"])
    return rows


def _compute_duplicate_occurrence_records(
    data_type: str,
    *,
    ip_name: Optional[str] = None,
) -> Optional[list[dict]]:
    """Full per-occurrence records behind total_duplicate_occurrences: one
    entry per actual duplicate row (not one per distinct CNIC), each
    carrying the CNIC, which IP it came from, and the full cleaned-file
    row it corresponds to.

        [
          {"cnic": "4320411145098", "ip_name": "safco", "record": {...}},
          {"cnic": "4320411145098", "ip_name": "trdp",  "record": {...}},
          ...
        ]

    Restricted to rows whose CNIC is already known to be a duplicate (via
    the shared pool) — this is a second scan of every IP's
    _cleaned.parquet, but each file is only re-filtered down to the rows
    that matter, not fully materialized again beyond that.

    `ip_name`, if given, restricts the scan to just that one IP's cleaned
    file (case-insensitive match) instead of every IP under this
    data_type — e.g. ip_name="Hands" only returns Hands' own duplicate-CNIC
    occurrences, skipping every other IP's file entirely.

    The full (unfiltered) result is cached separately from the summary
    pool, keyed by the same (path, mtime) signature, since it's heavier
    (full rows, not just counts) and only computed on demand. The
    ip_name-filtered view is derived from that same cached full list
    rather than triggering its own separate scan/cache.
    """
    pool = _compute_duplicate_cnic_pool(data_type)
    if pool is None:
        return None

    duplicate_cnics = pool["duplicate_cnics"]
    if not duplicate_cnics:
        return []

    candidates = _cleaned_candidates(data_type)
    if not candidates:
        return None

    signature = _signature(candidates)

    with _cnic_occurrence_lock:
        cached = _cnic_occurrence_cache.get(data_type.lower())
        if cached and cached[0] == signature:
            records = cached[1]
        else:
            records = None

    if records is None:
        records = []
        for ip_key_raw, file_id, path in candidates:
            try:
                df = pd.read_parquet(path, engine="fastparquet")
            except Exception:
                continue

            cnic_col = _find_cnic_column(df)
            if cnic_col is None:
                continue

            ip_key = ip_key_raw or file_id
            normalized = df[cnic_col].map(_normalize_cnic)
            mask = normalized.isin(duplicate_cnics.keys())
            if not mask.any():
                continue

            subset = df[mask].where(pd.notna(df[mask]), None)
            matched_cnics = normalized[mask]
            for (_, row), cnic in zip(subset.iterrows(), matched_cnics):
                records.append({
                    "cnic": cnic,
                    "ip_name": ip_key,
                    "record": row.to_dict(),
                })

        records.sort(key=lambda r: (r["cnic"], r["ip_name"]))

        with _cnic_occurrence_lock:
            _cnic_occurrence_cache[data_type.lower()] = (signature, records)

    if ip_name:
        target = ip_name.strip().lower()
        records = [r for r in records if r["ip_name"].lower() == target]

    return records


def _compute_missing_cnic_records(
    data_type: str,
    *,
    ip_name: Optional[str] = None,
) -> Optional[list[dict]]:
    """Full rows whose CNIC came back missing/null after normalization
    (blank, NaN, "N/A", etc. — see _normalize_cnic), one entry per row:

        [
          {"ip_name": "safco", "record": {...}},
          ...
        ]

    Backs the "Missing CNICs" total-records card (15,030-style, no
    ip_name) and the "Null CNIC in IP Records" per-IP card (0-style, with
    ip_name) — both are just this same list, unfiltered vs. filtered to
    one IP. The counts here match pool["missing_cnics_count"] /
    pool["missing_by_ip"] exactly, since both are computed from the same
    normalization pass; this just keeps the actual rows instead of only
    the counts.

    `ip_name`, if given, restricts to only that IP's own cleaned file
    (case-insensitive), same filtering behavior as the other drill-downs.

    The full (unfiltered) result is cached by the same (path, mtime)
    signature as the other drill-down caches, so repeat calls are served
    from memory until a contributing file changes.
    """
    candidates = _cleaned_candidates(data_type)
    if not candidates:
        return None

    signature = _signature(candidates)

    with _cnic_missing_lock:
        cached = _cnic_missing_cache.get(data_type.lower())
        if cached and cached[0] == signature:
            records = cached[1]
        else:
            records = None

    if records is None:
        records = []
        for ip_key_raw, file_id, path in candidates:
            try:
                df = pd.read_parquet(path, engine="fastparquet")
            except Exception:
                continue

            cnic_col = _find_cnic_column(df)
            if cnic_col is None:
                continue

            ip_key = ip_key_raw or file_id
            normalized = df[cnic_col].map(_normalize_cnic)
            mask = normalized.isna()
            if not mask.any():
                continue

            subset = df[mask].where(pd.notna(df[mask]), None)
            for _, row in subset.iterrows():
                records.append({
                    "ip_name": ip_key,
                    "record": row.to_dict(),
                })

        records.sort(key=lambda r: r["ip_name"])

        with _cnic_missing_lock:
            _cnic_missing_cache[data_type.lower()] = (signature, records)

    if ip_name:
        target = ip_name.strip().lower()
        records = [r for r in records if r["ip_name"].lower() == target]

    return records


def _get_ip_wise_summary(data_type: str, ip_name: str) -> Optional[dict]:
    """Same duplicate-CNIC pool as the aggregate summary, but scoped to a
    single IP — the numbers you'd get if you only cared about this IP's
    contribution to the picture:

        {
          "duplicate_cnic_in_IP": int,             # distinct duplicate CNICs
                                                     #   this IP has any rows for
          "null_cnic_in_IP": int,                   # missing-CNIC rows in
                                                     #   this IP's own report
          "duplicate_cnic_occurrence_in_IP": int,   # total occurrences of
                                                     #   duplicate CNICs
                                                     #   contributed by this IP
        }

    Matching is case-insensitive against pool keys, since the pool preserves
    whatever casing iter_all_outputs yielded for the folder name.

    Returns None if the pool itself is unavailable (no report files at all
    for this data_type) — a valid ip_name that simply has zero duplicates
    still returns real zeros, not None.
    """
    pool = _compute_duplicate_cnic_pool(data_type)
    if pool is None:
        return None

    target = (ip_name or "").strip().lower()

    duplicate_cnic_in_ip = 0
    duplicate_cnic_occurrence_in_ip = 0
    for ip_counts in pool["duplicate_cnics"].values():
        for k, count in ip_counts.items():
            if k.lower() == target:
                duplicate_cnic_in_ip += 1
                duplicate_cnic_occurrence_in_ip += count
                break  # only one entry per cnic can match this ip

    null_cnic_in_ip = 0
    for k, count in pool["missing_by_ip"].items():
        if k.lower() == target:
            null_cnic_in_ip = count
            break

    return {
        "duplicate_cnic_in_IP": duplicate_cnic_in_ip,
        "null_cnic_in_IP": null_cnic_in_ip,
        "duplicate_cnic_occurrence_in_IP": duplicate_cnic_occurrence_in_ip,
    }



def _output_path(data_type: str, file_id: str, kind: str, ip_name: Optional[str] = None) -> Path:
    """Resolve the on-disk path for a given output kind ('report' | 'duplicates' | ...).

    Centralizes the file_id sanitization + folder resolution that used to
    live only in _report_path, so every output kind shares one path-safety
    check instead of each endpoint reimplementing it slightly differently.
    """
    if "/" in file_id or "\\" in file_id or ".." in file_id:
        raise HTTPException(400, "Invalid file_id.")
    try:
        folder = resolve_dir(data_type, ip_name, create=False)
    except InvalidDataLocation as e:
        raise HTTPException(400, str(e))
    return folder / f"{file_id}_{kind}.parquet"


def _report_path(data_type: str, file_id: str, ip_name: Optional[str] = None) -> Path:
    return _output_path(data_type, file_id, "report", ip_name)


def _get_sorted_df(data_type: str, file_id: str, ip_name: Optional[str] = None) -> pd.DataFrame:
    path = _report_path(data_type, file_id, ip_name)
    if not path.exists():
        raise HTTPException(404, f"No report parquet for file_id '{file_id}'.")

    mtime = path.stat().st_mtime
    key = str(path)

    with _cache_lock:
        cached = _cache.get(key)
        if cached and cached[0] == mtime:
            return cached[1]

    try:
        df = load_report(path)
    except (KeyError, FileNotFoundError) as e:
        raise HTTPException(422, f"Could not read report: {e}")

    with _cache_lock:
        _cache[key] = (mtime, df)
    return df


def _get_duplicates_df(data_type: str, file_id: str, ip_name: Optional[str] = None) -> pd.DataFrame:
    path = _output_path(data_type, file_id, "duplicates", ip_name)
    if not path.exists():
        raise HTTPException(404, f"No duplicates parquet for file_id '{file_id}'.")

    mtime = path.stat().st_mtime
    key = str(path)

    with _dup_cache_lock:
        cached = _dup_cache.get(key)
        if cached and cached[0] == mtime:
            return cached[1]

    try:
        df = pd.read_parquet(path, engine="fastparquet")
    except Exception as e:
        raise HTTPException(422, f"Could not read duplicates file: {e}")

    with _dup_cache_lock:
        _dup_cache[key] = (mtime, df)
    return df


@router.get("/{data_type}/{ip_name}/{file_id}/page", summary="Fetch one cursor-paginated page (beneficiary / banks / financials)")
@router.get("/{data_type}/{file_id}/page", summary="Fetch one cursor-paginated page (certificates)")
async def get_report_page(
    data_type: str,
    file_id: str,
    ip_name: Optional[str] = None,
    page_size: int = Query(default=20, ge=1, le=5000, description="Rows per page"),
    cursor: Optional[str] = Query(default=None, description="Opaque token from a previous page's next_cursor"),
    page: Optional[int] = Query(default=None, ge=1, description="Jump directly to this 1-based page number, computed from page_size — e.g. page_size=500 on 2,000 rows gives 4 pages, and page=4 jumps straight there without paging through 1-3. Takes precedence over cursor if both are given."),
    raw: bool = Query(default=False, description="Return JSON columns as raw strings instead of nested objects"),
):
    df = _get_sorted_df(data_type, file_id, ip_name)
    try:
        page_result = get_page(df, page_size=page_size, cursor=cursor, decode_json=not raw, page=page)
    except ValueError as e:
        raise HTTPException(400, str(e))
    page_result["file_id"]   = file_id
    page_result["data_type"] = data_type.lower()
    page_result["ip_name"]   = ip_name

    # Attach validation summary from sidecar JSON if present
    try:
        out_dir = resolve_dir(data_type, ip_name, create=False)
        sidecar = out_dir / f"{file_id}_validation_summary.json"
        if sidecar.exists():
            page_result["validation_summary"] = json.loads(sidecar.read_text())
    except Exception:
        pass

    # Attach the live-computed duplicate-CNIC summary, aggregated across
    # every IP's own _report.parquet for this data_type — no more
    # hardcoded global file, and no reliance on _duplicates.parquet (which
    # lacks the CNIC/is_dup_cnic data needed for this).
    duplicate_cnic_summary = _get_duplicate_cnic_summary(data_type)
    if duplicate_cnic_summary is not None:
        page_result["duplicate_cnic_summary"] = duplicate_cnic_summary

    # Same underlying pool, but scoped to just the IP in this URL — e.g.
    # /beneficiary/Trdp/Trdp/page gives Trdp-only numbers here, while
    # duplicate_cnic_summary above stays the all-IP aggregate.
    if ip_name:
        ip_wise_summary = _get_ip_wise_summary(data_type, ip_name)
        if ip_wise_summary is not None:
            page_result["ip_wise_summary"] = ip_wise_summary

    return JSONResponse(page_result)


@router.get("/{data_type}/{ip_name}/{file_id}/duplicates",
            summary="Fetch the entire duplicates file as JSON — no pagination (beneficiary / banks / financials)")
@router.get("/{data_type}/{file_id}/duplicates",
            summary="Fetch the entire duplicates file as JSON — no pagination (certificates)")
async def get_duplicates_full(
    data_type: str,
    file_id: str,
    ip_name: Optional[str] = None,
):
    df = _get_duplicates_df(data_type, file_id, ip_name)
    # NaN/NaT aren't valid JSON tokens — coerce to None before serializing,
    # same as write_outputs() already does when it writes the parquet, but
    # cheap insurance against any dtype that slips a float NaN through.
    records = df.where(pd.notna(df), None).to_dict(orient="records")

    response_payload = {
        "data_type":  data_type.lower(),
        "ip_name":    ip_name,
        "file_id":    file_id,
        "total_rows": len(records),
        "rows":       records,
    }

    # Attach the per-CNIC duplicate breakdown here — NOT the aggregate
    # summary (that block belongs only to /page). Computed globally across
    # every IP under this data_type, same underlying scan as /page uses,
    # just shaped as a flat per-CNIC list instead of rolled-up totals.
    # Silently omitted if unavailable.
    duplicate_cnic_data = _get_duplicate_cnic_data(data_type)
    if duplicate_cnic_data is not None:
        response_payload["data"] = duplicate_cnic_data

    return JSONResponse(response_payload)


# ---------------------------------------------------------------------------
# Duplicate-CNIC drill-down endpoints
#
# Each one backs exactly one number in duplicate_cnic_summary (see /page),
# and all four share the same page/cursor/page_size contract as /page —
# including direct page-number jumps — via paginate_list.
# ---------------------------------------------------------------------------

def _paginate_or_400(items: list[dict], page_size: int, cursor: Optional[str], page: Optional[int]) -> dict:
    try:
        return paginate_list(items, page_size=page_size, cursor=cursor, page=page)
    except ValueError as e:
        raise HTTPException(400, str(e))


_IP_NAME_FILTER_DESC = (
    "Optional — restrict results to just this one IP (e.g. 'Hands'), "
    "case-insensitive. Omit to see every IP pooled together."
)


@router.get("/{data_type}/duplicates/cnic/records",
            summary="Paginated per-CNIC duplicate list — backs total_duplicate_cnic_records")
async def get_duplicate_cnic_records(
    data_type: str,
    page_size: int = Query(default=20, ge=1, le=5000),
    cursor: Optional[str] = Query(default=None),
    page: Optional[int] = Query(default=None, ge=1, description="Jump directly to this 1-based page."),
    ip_name: Optional[str] = Query(default=None, description=_IP_NAME_FILTER_DESC),
):
    """One row per distinct duplicate CNIC (2,317-style total). Each row
    carries duplicate_count (total occurrences) and which IP(s) it showed
    up in — this is the same shape as /duplicates' `data` field, just
    paginated instead of returned as one giant array.

    Pass ip_name to restrict to CNICs involving that one IP — e.g.
    ?ip_name=Hands returns only duplicate CNICs that Hands has at least
    one occurrence of (whether the duplicate is entirely within Hands or
    spans other IPs too).
    """
    items = _get_duplicate_cnic_data(data_type, ip_name=ip_name)
    if items is None:
        raise HTTPException(404, f"No cleaned data found for data_type '{data_type}'.")
    result = _paginate_or_400(items, page_size, cursor, page)
    result["data_type"] = data_type.lower()
    result["ip_name_filter"] = ip_name
    return JSONResponse(result)


@router.get("/{data_type}/duplicates/cnic/occurrences",
            summary="Paginated full-row occurrences of every duplicate CNIC — backs total_duplicate_occurrences")
async def get_duplicate_cnic_occurrences(
    data_type: str,
    page_size: int = Query(default=20, ge=1, le=5000),
    cursor: Optional[str] = Query(default=None),
    page: Optional[int] = Query(default=None, ge=1, description="Jump directly to this 1-based page."),
    ip_name: Optional[str] = Query(default=None, description=_IP_NAME_FILTER_DESC),
):
    """One row PER OCCURRENCE, not per distinct CNIC (4,638-style total) —
    the full underlying cleaned-file record for every duplicate row, along
    with which CNIC and which IP it belongs to. A CNIC duplicated 3 times
    contributes 3 separate entries here.

    Pass ip_name (e.g. ?ip_name=Hands) to see only the occurrences that
    physically live in that IP's own cleaned file — e.g. a CNIC duplicated
    once in Hands and once in Trdp would show just the Hands row here.

    Heavier than /records: pulls the full row, not just a summary, for
    every occurrence, so the unfiltered result is cached the same way as
    the summary pool (invalidated automatically whenever a contributing
    file changes); the ip_name filter is applied on top of that cache.
    """
    items = _compute_duplicate_occurrence_records(data_type, ip_name=ip_name)
    if items is None:
        raise HTTPException(404, f"No cleaned data found for data_type '{data_type}'.")
    result = _paginate_or_400(items, page_size, cursor, page)
    result["data_type"] = data_type.lower()
    result["ip_name_filter"] = ip_name
    return JSONResponse(result)


@router.get("/{data_type}/duplicates/cnic/single-ip",
            summary="Paginated CNICs duplicated within one IP only — backs cnics_duplicated_in_single_ip")
async def get_duplicate_cnic_single_ip(
    data_type: str,
    page_size: int = Query(default=20, ge=1, le=5000),
    cursor: Optional[str] = Query(default=None),
    page: Optional[int] = Query(default=None, ge=1, description="Jump directly to this 1-based page."),
    ip_name: Optional[str] = Query(default=None, description=_IP_NAME_FILTER_DESC),
):
    """CNICs that repeat 2+ times but only ever within a single IP's own
    data (2,263-style total) — i.e. this IP's own cleaning run should have
    already flagged these itself; they aren't cross-IP surprises.

    Pass ip_name (e.g. ?ip_name=Hands) to see only Hands' own single-IP
    duplicates instead of every IP's pooled together.
    """
    items = _get_duplicate_cnic_data(data_type, only="single_ip", ip_name=ip_name)
    if items is None:
        raise HTTPException(404, f"No cleaned data found for data_type '{data_type}'.")
    result = _paginate_or_400(items, page_size, cursor, page)
    result["data_type"] = data_type.lower()
    result["ip_name_filter"] = ip_name
    return JSONResponse(result)


@router.get("/{data_type}/duplicates/cnic/cross-ip",
            summary="Paginated CNICs duplicated across 2+ IPs — backs cnics_duplicated_across_multiple_ips")
async def get_duplicate_cnic_cross_ip(
    data_type: str,
    page_size: int = Query(default=20, ge=1, le=5000),
    cursor: Optional[str] = Query(default=None),
    page: Optional[int] = Query(default=None, ge=1, description="Jump directly to this 1-based page."),
    ip_name: Optional[str] = Query(default=None, description=_IP_NAME_FILTER_DESC),
):
    """CNICs that show up in 2+ *different* IPs (54-style total) — the
    genuine cross-IP duplicates that no single IP's own per-file cleaning
    run could ever catch on its own.

    Pass ip_name (e.g. ?ip_name=Hands) to see only the cross-IP duplicates
    that Hands happens to be one of the involved IPs for.
    """
    items = _get_duplicate_cnic_data(data_type, only="cross_ip", ip_name=ip_name)
    if items is None:
        raise HTTPException(404, f"No cleaned data found for data_type '{data_type}'.")
    result = _paginate_or_400(items, page_size, cursor, page)
    result["data_type"] = data_type.lower()
    result["ip_name_filter"] = ip_name
    return JSONResponse(result)


@router.get("/{data_type}/duplicates/cnic/missing",
            summary="Paginated full rows with a missing/null CNIC — backs Missing CNICs (global) and Null CNIC in IP Records (per-IP)")
async def get_missing_cnic_records(
    data_type: str,
    page_size: int = Query(default=20, ge=1, le=5000),
    cursor: Optional[str] = Query(default=None),
    page: Optional[int] = Query(default=None, ge=1, description="Jump directly to this 1-based page."),
    ip_name: Optional[str] = Query(default=None, description=_IP_NAME_FILTER_DESC),
):
    """Full underlying cleaned-file row for every record whose CNIC came
    back blank/NaN/"N/A"/etc. after normalization (15,030-style total with
    no ip_name filter). Pass ip_name (e.g. ?ip_name=Hands) to scope this to
    just that IP's own missing-CNIC rows instead — the count then matches
    ip_wise_summary.null_cnic_in_IP from /page for that same IP.
    """
    items = _compute_missing_cnic_records(data_type, ip_name=ip_name)
    if items is None:
        raise HTTPException(404, f"No cleaned data found for data_type '{data_type}'.")
    result = _paginate_or_400(items, page_size, cursor, page)
    result["data_type"] = data_type.lower()
    result["ip_name_filter"] = ip_name
    return JSONResponse(result)


def _get_cleaned_df(data_type: str, file_id: str, ip_name: Optional[str] = None) -> pd.DataFrame:
    path = _output_path(data_type, file_id, "cleaned", ip_name)
    if not path.exists():
        raise HTTPException(404, f"No cleaned parquet for file_id '{file_id}'.")
    try:
        return pd.read_parquet(path, engine="fastparquet")
    except Exception as e:
        raise HTTPException(422, f"Could not read cleaned file: {e}")


@router.get("/{data_type}/{ip_name}/{file_id}/records",
            summary="Fetch full records sharing this CNIC, within this IP's own cleaned file (beneficiary / banks / financials)")
@router.get("/{data_type}/{file_id}/records",
            summary="Fetch full records sharing this CNIC, within this file's own cleaned data (certificates)")
async def get_records_by_cnic(
    data_type: str,
    file_id: str,
    ip_name: Optional[str] = None,
    cnic: str = Query(..., description="CNIC to look up — dashes/spaces are fine, normalized automatically"),
):
    """Given a CNIC, find and return the full record for every row within
    this specific IP's own _cleaned.parquet whose CNIC (after
    normalization) matches it — e.g. a CNIC that repeats 3 times within
    this IP returns all 3 full rows.

    Scoped to a single IP, same URL shape as /page and /duplicates — this
    does NOT search other IPs. Use /{data_type}/cnic/records?cnic=... (no
    ip_name/file_id) if you want the cross-IP lookup instead.

    Reads from _cleaned.parquet: every field is a plain column (including
    the CNIC column itself, e.g. "DA_CNIC") with no JSON-encoded values to
    decode, so a match here is a direct row dump — no json.loads() needed.

    The CNIC is normalized the same way as everywhere else (whitespace/
    dashes stripped, float ".0" artifacts removed), so "4530-358-104832"
    and "4530358104832" both resolve to the same lookup.
    """
    target = _normalize_cnic(cnic)
    if target is None:
        raise HTTPException(400, f"'{cnic}' does not look like a valid CNIC.")

    df = _get_cleaned_df(data_type, file_id, ip_name)

    cnic_col = _find_cnic_column(df)
    if cnic_col is None:
        raise HTTPException(422, f"No CNIC-like column found in cleaned file for '{file_id}'.")

    normalized = df[cnic_col].map(_normalize_cnic)
    mask = normalized == target

    if not mask.any():
        raise HTTPException(
            404,
            f"No records found with CNIC '{cnic}' in '{ip_name or file_id}'.",
        )

    subset = df[mask].where(pd.notna(df[mask]), None)
    records = [
        {"ip_name": ip_name or file_id, **record}
        for record in subset.to_dict(orient="records")
    ]

    return JSONResponse({
        "data_type": data_type.lower(),
        "ip_name": ip_name,
        "file_id": file_id,
        "cnic": target,
        "duplicate_count": len(records),
        "records": records,
    })


@router.get("/", summary="List available report file_ids across every type/IP folder")
async def list_reports():
    files = sorted(iter_all_outputs(kind="report"), key=lambda t: t[2])
    return {
        "reports": [
            {"data_type": data_type, "ip_name": ip_name, "file_id": file_id,
             "file": p.name, "size_mb": round(p.stat().st_size / 1024 / 1024, 2)}
            for data_type, ip_name, file_id, p in files
        ],
    }


@router.delete("/{data_type}/{ip_name}/{file_id}/cache", summary="Evict a report + duplicates from the in-process cache")
@router.delete("/{data_type}/{file_id}/cache", summary="Evict a report + duplicates from the in-process cache (certificates)")
async def evict_cache(data_type: str, file_id: str, ip_name: Optional[str] = None):
    report_key = str(_output_path(data_type, file_id, "report", ip_name))
    dup_key    = str(_output_path(data_type, file_id, "duplicates", ip_name))
    with _cache_lock:
        evicted_report = _cache.pop(report_key, None) is not None
    with _dup_cache_lock:
        evicted_duplicates = _dup_cache.pop(dup_key, None) is not None

    # Also drop this data_type's aggregated CNIC-summary cache and the
    # occurrence-records cache, since an evicted report file may be about
    # to be rewritten.
    with _cnic_summary_lock:
        _cnic_summary_cache.pop(data_type.lower(), None)
    with _cnic_occurrence_lock:
        _cnic_occurrence_cache.pop(data_type.lower(), None)
    with _cnic_missing_lock:
        _cnic_missing_cache.pop(data_type.lower(), None)

    return {
        "data_type": data_type.lower(), "ip_name": ip_name, "file_id": file_id,
        "evicted_report": evicted_report, "evicted_duplicates": evicted_duplicates,
    }